### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by pruge**

### CODE REVIEW

**Comment by zhuangya** [comment]
maybe you mean `bcrypt`?

**Comment by janez89** [comment]
bcrypt was you wanted to upgrade?

**Comment by zhuangya** [comment]
bcrypt could be a problem if i run on node `0.12.x`
i have to update bcrypt version in `mongoose-utilites` package.json :(

**Comment by janez89** [comment]
I'm updated package.json and uploaded to the npmjs.com
A few minutes and can be download with npm.

I closed this thread because mistyped the name of the package :)

**Pull request closed without merging**
